apiVersion: v1
kind: Service
metadata:
  name: limospay-customer-web
  labels:
    app: limospay-customer-web
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: limospay-customer-web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: limospay-customer-web
  labels:
    app: limospay-customer-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: limospay-customer-web
  template:
    metadata:
      labels:
        app: limospay-customer-web
    spec:
      containers:
      - name: limospay-customer-web
        image: 863852973330.dkr.ecr.eu-west-2.amazonaws.com/limospay-customer-web:imgtag
        env:
        - name: MESSAGING_GROUP_ID
          value: "events" 
        ports: 
        - name: http
          containerPort: 80
      imagePullSecrets:
      - name: dynamowit
